# Generated by Django 5.2.15 on 2026-07-17 01:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraphSpace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', max_length=16)),
                ('graph_backend', models.CharField(choices=[('neo4j', 'Neo4j'), ('file', 'File'), ('postgres_graph', 'Postgres Graph')], default='neo4j', max_length=32)),
                ('graph_ref', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'api_graphspace',
                'ordering': ['title', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='GraphView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('layout_mode', models.CharField(choices=[('manual', 'Manual'), ('force', 'Force'), ('hierarchy', 'Hierarchy'), ('radial', 'Radial')], default='manual', max_length=32)),
                ('is_default', models.BooleanField(default=False)),
                ('viewport_x', models.FloatField(blank=True, null=True)),
                ('viewport_y', models.FloatField(blank=True, null=True)),
                ('zoom', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'api_graphview',
                'ordering': ['-is_default', 'title', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='GraphViewNodePosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_id', models.CharField(max_length=255)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('pinned', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('collapsed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'api_graphviewnodeposition',
                'ordering': ['node_id'],
            },
        ),
    ]
