# Generated by Django 5.2.15 on 2026-07-17 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('graphs', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphspace',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph_spaces', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='graphview',
            name='graph_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='graphs.graphspace'),
        ),
        migrations.AddField(
            model_name='graphviewnodeposition',
            name='graph_view',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_positions', to='graphs.graphview'),
        ),
        migrations.AddConstraint(
            model_name='graphspace',
            constraint=models.UniqueConstraint(fields=('workspace', 'title'), name='unique_graph_space_title_per_workspace'),
        ),
        migrations.AddConstraint(
            model_name='graphview',
            constraint=models.UniqueConstraint(fields=('graph_space', 'title'), name='unique_graph_view_title_per_graph_space'),
        ),
        migrations.AddConstraint(
            model_name='graphview',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('graph_space',), name='unique_default_graph_view_per_graph_space'),
        ),
        migrations.AddConstraint(
            model_name='graphviewnodeposition',
            constraint=models.UniqueConstraint(fields=('graph_view', 'node_id'), name='unique_node_position_per_graph_view'),
        ),
    ]
