# Generated by Django 5.2.15 on 2026-07-20 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graphs", "0002_initial"),
        ("workspaces", "0002_alter_workspace_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="graphspace",
            name="graph_backend",
            field=models.CharField(
                choices=[
                    ("neo4j", "Neo4j"),
                    ("file", "File"),
                    ("postgres_graph", "Postgres Graph"),
                ],
                default="postgres_graph",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="graphspace",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("draft", "Draft"),
                    ("suggested", "Suggested"),
                    ("archived", "Archived"),
                    ("deleted", "Deleted"),
                ],
                default="active",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="GraphNode",
            fields=[
                ("node_id", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("draft", "Draft"),
                            ("suggested", "Suggested"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("shared", "Shared"),
                            ("public", "Public"),
                        ],
                        default="private",
                        max_length=16,
                    ),
                ),
                ("language", models.CharField(default="es-MX", max_length=16)),
                ("manual", models.BooleanField(default=False)),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("document", "Document"),
                            ("section", "Section"),
                            ("content", "Content"),
                            ("chunk", "Chunk"),
                            ("concept", "Concept"),
                        ],
                        max_length=32,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("schema_version", models.PositiveIntegerField(default=1)),
                ("content_json", models.JSONField(blank=True, null=True)),
                ("content_markdown", models.TextField(blank=True)),
                ("content_text", models.TextField(blank=True)),
                ("content_version", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "source_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("upload", "Upload"),
                            ("url", "URL"),
                            ("manual", "Manual"),
                            ("generated", "Generated"),
                            ("import", "Import"),
                        ],
                        max_length=16,
                    ),
                ),
                ("source_path", models.TextField(blank=True)),
                ("source_url", models.TextField(blank=True)),
                ("source_extension", models.CharField(blank=True, max_length=16)),
                (
                    "processing_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("word_count", models.IntegerField(blank=True, null=True)),
                ("character_count", models.IntegerField(blank=True, null=True)),
                ("chunk_count", models.IntegerField(blank=True, null=True)),
                ("page_count", models.IntegerField(blank=True, null=True)),
                ("mime_type", models.CharField(blank=True, max_length=120)),
                ("document_title_original", models.CharField(blank=True, max_length=64)),
                ("level", models.IntegerField(blank=True, null=True)),
                ("order", models.IntegerField(blank=True, null=True)),
                ("start_position", models.IntegerField(blank=True, null=True)),
                ("end_position", models.IntegerField(blank=True, null=True)),
                ("summary", models.TextField(blank=True)),
                (
                    "node_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("note", "Note"),
                            ("idea", "Idea"),
                            ("explanation", "Explanation"),
                            ("definition", "Definition"),
                            ("theorem", "Theorem"),
                            ("synthesis", "Synthesis"),
                        ],
                        max_length=64,
                    ),
                ),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("semantic_hash", models.CharField(blank=True, max_length=128)),
                ("embedding_id", models.CharField(blank=True, max_length=255)),
                ("embedding_model", models.CharField(blank=True, max_length=120)),
                ("embedding_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "chunk_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("paragraph", "Paragraph"),
                            ("table", "Table"),
                            ("formula", "Formula"),
                            ("merged_paragraphs", "Merged paragraphs"),
                            ("code", "Code"),
                        ],
                        max_length=64,
                    ),
                ),
                ("token_count", models.IntegerField(blank=True, null=True)),
                ("source_hash", models.CharField(blank=True, max_length=128)),
                ("normalized_name", models.CharField(blank=True, max_length=64)),
                ("description", models.TextField(blank=True)),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("domain", models.CharField(blank=True, max_length=64)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("frequency", models.IntegerField(blank=True, null=True)),
                ("extraction_method", models.CharField(blank=True, max_length=32)),
                (
                    "concept_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("term", "Term"),
                            ("person", "Person"),
                            ("theory", "Theory"),
                            ("formula", "Formula"),
                            ("process", "Process"),
                            ("event", "Event"),
                            ("method", "Method"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_graph_nodes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        db_column="document_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_children",
                        to="graphs.graphnode",
                    ),
                ),
                (
                    "graph_space",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="graphs.graphspace",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        db_column="section_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="section_chunks",
                        to="graphs.graphnode",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_graph_nodes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graph_nodes",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "graph_node",
                "ordering": ["node_type", "order", "title"],
            },
        ),
        migrations.CreateModel(
            name="GraphRelationship",
            fields=[
                ("relationship_id", models.CharField(max_length=255, primary_key=True, serialize=False)),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("CONTAINS", "Contains"),
                            ("REFERENCES", "References"),
                            ("RELATES", "Relates"),
                            ("DEPENDS_ON", "Depends on"),
                            ("EVALUATES", "Evaluates"),
                        ],
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("draft", "Draft"),
                            ("suggested", "Suggested"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("manual", models.BooleanField(default=False)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("weight", models.FloatField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                ("evidence", models.JSONField(blank=True, null=True)),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("manual", "Manual"),
                            ("parser", "Parser"),
                            ("embedding", "Embedding"),
                            ("llm", "LLM"),
                            ("import", "Import"),
                            ("system", "System"),
                        ],
                        max_length=32,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("role", models.CharField(max_length=32)),
                ("schema_version", models.PositiveIntegerField(default=1)),
                ("order", models.IntegerField(blank=True, null=True)),
                ("similarity_score", models.FloatField(blank=True, null=True)),
                ("semantic_distance", models.FloatField(blank=True, null=True)),
                ("bidirectional", models.BooleanField(default=False)),
                ("relation_label", models.CharField(blank=True, max_length=64)),
                ("difficulty_gap", models.FloatField(blank=True, null=True)),
                ("strength", models.FloatField(blank=True, null=True)),
                ("blocking", models.BooleanField(default=False)),
                ("coverage", models.FloatField(blank=True, null=True)),
                ("difficulty", models.IntegerField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_graph_relationships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "graph_space",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships",
                        to="graphs.graphspace",
                    ),
                ),
                (
                    "source_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relationships",
                        to="graphs.graphnode",
                    ),
                ),
                (
                    "target_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relationships",
                        to="graphs.graphnode",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_graph_relationships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graph_relationships",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "graph_relationship",
                "ordering": ["relationship_type", "order", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="graphnode",
            index=models.Index(fields=["workspace", "node_type"], name="graph_node_workspa_468d97_idx"),
        ),
        migrations.AddIndex(
            model_name="graphnode",
            index=models.Index(fields=["graph_space", "node_type"], name="graph_node_graph_s_8080ee_idx"),
        ),
        migrations.AddIndex(
            model_name="graphnode",
            index=models.Index(fields=["document", "order"], name="graph_node_documen_d7b086_idx"),
        ),
        migrations.AddIndex(
            model_name="graphnode",
            index=models.Index(fields=["normalized_name"], name="graph_node_normali_6d68ad_idx"),
        ),
        migrations.AddIndex(
            model_name="graphnode",
            index=models.Index(fields=["status"], name="graph_node_status_d83233_idx"),
        ),
        migrations.AddIndex(
            model_name="graphrelationship",
            index=models.Index(
                fields=["workspace", "relationship_type"],
                name="graph_relat_workspa_240509_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="graphrelationship",
            index=models.Index(
                fields=["graph_space", "relationship_type"],
                name="graph_relat_graph_s_30b878_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="graphrelationship",
            index=models.Index(
                fields=["source_node", "relationship_type"],
                name="graph_relat_source__6e806d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="graphrelationship",
            index=models.Index(
                fields=["target_node", "relationship_type"],
                name="graph_relat_target__968bb2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="graphrelationship",
            index=models.Index(fields=["status"], name="graph_relat_status_cc5307_idx"),
        ),
    ]
