# Generated by Codex on 2026-07-20

from django.db import migrations, models


def set_graphspaces_to_neo4j(apps, schema_editor):
    graph_space = apps.get_model("graphs", "GraphSpace")
    graph_space.objects.update(graph_backend="neo4j")


class Migration(migrations.Migration):

    dependencies = [
        ("graphs", "0003_alter_graphspace_graph_backend_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graphspace",
            name="graph_backend",
            field=models.CharField(
                choices=[
                    ("neo4j", "Neo4j"),
                    ("file", "File"),
                    ("postgres_graph", "Postgres Graph"),
                ],
                default="neo4j",
                max_length=32,
            ),
        ),
        migrations.RunPython(set_graphspaces_to_neo4j, migrations.RunPython.noop),
    ]
