# Generated by Codex on 2026-07-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graphs", "0004_set_graphspace_backend_neo4j"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GraphRelationship",
        ),
        migrations.DeleteModel(
            name="GraphNode",
        ),
        migrations.AlterField(
            model_name="graphspace",
            name="graph_backend",
            field=models.CharField(
                choices=[
                    ("neo4j", "Neo4j"),
                    ("file", "File"),
                ],
                default="neo4j",
                max_length=32,
            ),
        ),
    ]
