# Generated by Django 5.2.15 on 2026-07-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("draft", "Draft"),
                    ("suggested", "Suggested"),
                    ("archived", "Archived"),
                    ("deleted", "Deleted"),
                ],
                default="active",
                max_length=16,
            ),
        ),
    ]
